name: PythonPackage

on:
  push:
    tags:
      - 'v*'   # Triggers on version tags like v1.0.0, v2.0.1, etc.

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel build twine pytest

      - name: Install package dependencies for testing
        run: |
          python -m pip install .[dev]

      - name: Run tests
        run: |
          pytest

      - name: Build distributions
        run: |
          python -m build

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload dist/*

